{{- $secrets := list -}}
{{- if and .Values.lhci.storage.sqlConnectionUrl (not .Values.lhci.storage.existingSecret.name) (not (or .Values.postgresql.enabled .Values.mysql.enabled)) -}}
{{- $secrets = append $secrets (dict "suffix" "database" "data" (dict "uri" .Values.lhci.storage.sqlConnectionUrl)) -}}
{{- end -}}
{{- if and .Values.lhci.basicAuth.enabled (not .Values.lhci.basicAuth.existingSecret.name) -}}
{{- $secrets = append $secrets (dict "suffix" "basic-auth" "data" (dict "username" .Values.lhci.basicAuth.username "password" .Values.lhci.basicAuth.password)) -}}
{{- end -}}
{{- if and .Values.lhci.psiCollectCron.sites (not .Values.lhci.psiCollectCron.existingSecret.name) -}}
{{- $secrets = append $secrets (dict "suffix" "psi" "data" (dict "apiKey" .Values.lhci.psiCollectCron.psiApiKey)) -}}
{{- end -}}
{{- range $secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lhci.suffixedName" (dict "context" $ "suffix" .suffix) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "lhci.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
